{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: ping*/}}
{{/*  labels:*/}}
{{/*    env  : prod*/}}
{{/*    owner: RomanCherevatenko*/}}
{{/*spec:*/}}
{{/*  selector:*/}}
{{/*    project: ping    # Selecting PODS with those Labels*/}}
{{/*  ports:*/}}
{{/*    - protocol  : TCP*/}}
{{/*      port      : 8089  # Port on Load Balancer*/}}
{{/*      targetPort: 8089  # Port on POD*/}}
